[project]
name = "kitefin"
version = "0.1.0"
description = "A C Compiler Written in Python"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff]
extend-exclude = ["tests"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "N"]